# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ARTEN
tagline:          'A Jekyll theme'
description:      'Be Happy'
url:              https://PKR-ARTEN.github.io
baseurl:          /

author:
  name:           'ARTEN'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

remote_theme :    poole/hyde